# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/42701c28-c857-4f68-883a-125c1e985b33";
      fsType = "btrfs";
      # 🎯 [OMEN] 2026-08-17 性能优化：compress=zstd:1（快速压缩，计算场景少占 CPU）+
      # noatime（SSD 减写）。旧数据不压缩，新写入生效；重装/重生成本文件会丢，注意保留
      options = [ "subvol=@" "compress=zstd:1" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/42701c28-c857-4f68-883a-125c1e985b33";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/42701c28-c857-4f68-883a-125c1e985b33";
      fsType = "btrfs";
      # /nix 不加 compress：store 内包本身已压缩，再压浪费 CPU
      options = [ "subvol=@nix" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/71C7-34C8";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
